import{useEffect,useRef,useState}from'react';
import type{PointerEvent as ReactPointerEvent,ReactNode}from'react';
import{Upload,Undo2,Redo2,Grid3X3,MousePointer2,PenTool,Link2,Ruler,Move,ZoomIn,Download,Sun,Moon,Play,Pause,Check,AlertTriangle,Layers,FolderOpen,CheckCircle2,XCircle,RefreshCw,Image as ImageIcon}from'lucide-react';
import type{Line,Project,BatchJob,ConnectionCandidate}from'./types';
import{optimize}from'./algorithms/sugarOptimizer';
import{analyze,recommendSticks}from'./algorithms/structure';
import{minimumPenLiftPath,rebuildGraph,penLifts,totalPathLength}from'./algorithms/skeletonGraph';
import{findConnectionCandidates,applyConnections}from'./algorithms/connections';
import{saveProject,listProjects}from'./storage/projectStore';
import{downloadSvg,planPdf,zipProjects}from'./export/exporters';
import{BatchProcessor}from'./batch/batchProcessor';

const defaults={detail:'balanced' as const,minWidthMm:3.5,connectDistance:.06,simplifyTolerance:.015};
const blank=():Project=>({id:crypto.randomUUID(),name:'Untitled Sugar Art',createdAt:Date.now(),updatedAt:Date.now(),lines:[],widthMm:300,heightMm:250,settings:defaults,warnings:[],sticks:[],connections:[],history:[]});
const cloneLines=(lines:Line[])=>lines.map(l=>({...l,points:l.points.map(p=>({...p}))}));
const normalize=(p:Project):Project=>({...p,connections:p.connections??[],history:p.history??[],warnings:p.warnings??[],sticks:p.sticks??[],settings:{...defaults,...p.settings}});

export default function App(){
 const[cursor,setCursor]=useState<'select'|'draw'|'connect'|'measure'|'pan'>('select'),[dark,setDark]=useState(true),[p,setP]=useState(blank),[projects,setProjects]=useState<Project[]>([]),[playing,setPlaying]=useState(false),[playIndex,setPlayIndex]=useState(0),[zoom,setZoom]=useState(1),[grid,setGrid]=useState(true),[snap,setSnap]=useState(true),[batchOpen,setBatchOpen]=useState(false),[batchJobs,setBatchJobs]=useState<BatchJob[]>([]),[viewMode,setViewMode]=useState<'result'|'original'|'overlay'>('result'),[overlayOpacity,setOverlayOpacity]=useState(.5),[selectedLine,setSelectedLine]=useState<string|null>(null),[selectedNode,setSelectedNode]=useState<{lineId:string;index:number}|null>(null),[connectStart,setConnectStart]=useState<string|null>(null),[dragging,setDragging]=useState(false),[nodeDragging,setNodeDragging]=useState(false),[dragStart,setDragStart]=useState({x:0,y:0}),canvas=useRef<HTMLCanvasElement>(null),raf=useRef<number|null>(null);
 useEffect(()=>{listProjects().then(xs=>{const n=xs.map(normalize);setProjects(n);if(n.length)setP(n[0])})},[]);
 useEffect(()=>{const t=window.setTimeout(()=>saveProject(p),250);setProjects(x=>[p,...x.filter(a=>a.id!==p.id)]);return()=>clearTimeout(t)},[p]);
 useEffect(()=>{if(!playing){if(raf.current)cancelAnimationFrame(raf.current);return}let last=performance.now();const tick=(now:number)=>{const dt=Math.min(50,now-last);last=now;setPlayIndex(i=>{const speed=Math.max(1,p.lines.length/18);const n=Math.min(p.lines.length,i+dt/1000*speed);if(n>=p.lines.length){setPlaying(false);return p.lines.length}return n});raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>{if(raf.current)cancelAnimationFrame(raf.current)}},[playing,p.lines.length]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const dpr=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d')!;x.setTransform(dpr,0,0,dpr,0,0);x.fillStyle=dark?'#101216':'#f4f5f7';x.fillRect(0,0,w,h);x.save();x.translate(w/2,h/2);x.scale(zoom,zoom);
  const sx=700,sy=700;
  if(grid){x.strokeStyle=dark?'#272b32':'#d9dde4';x.lineWidth=1;for(let i=-700;i<=700;i+=25){x.beginPath();x.moveTo(i,-500);x.lineTo(i,500);x.stroke();x.beginPath();x.moveTo(-700,i);x.lineTo(700,i);x.stroke()}}
  const drawLine=(l:Line,stroke='#171717',width=Math.max(1,l.width*1.5),alpha=1)=>{x.globalAlpha=alpha;x.strokeStyle=stroke;x.lineWidth=width;x.lineCap='round';x.lineJoin='round';x.beginPath();l.points.forEach((q,i)=>i?x.lineTo(q.x*sx,q.y*sy):x.moveTo(q.x*sx,q.y*sy));x.stroke();x.globalAlpha=1};
  p.lines.forEach(l=>drawLine(l,dark?'#f1f3f5':'#171717'));
  p.connections.filter(c=>c.status==='pending').forEach(c=>{const a=p.lines.find(l=>l.id===c.a),b=p.lines.find(l=>l.id===c.b);if(!a||!b)return;const ap=c.aEnd==='start'?a.points[0]:a.points.at(-1)!,bp=c.bEnd==='start'?b.points[0]:b.points.at(-1)!;x.save();x.setLineDash([8,6]);x.strokeStyle='#d99b28';x.lineWidth=2;x.beginPath();x.moveTo(ap.x*sx,ap.y*sy);x.lineTo(bp.x*sx,bp.y*sy);x.stroke();x.setLineDash([]);x.fillStyle='#d99b28';x.beginPath();x.arc(ap.x*sx,ap.y*sy,5,0,Math.PI*2);x.fill();x.beginPath();x.arc(bp.x*sx,bp.y*sy,5,0,Math.PI*2);x.fill();x.restore()});
  if(showNodes){const graph=rebuildGraph(p.lines);graph.forEach(n=>{const selected=n.id===selectedGraphNode;const r=selected?9:n.degree>=3?7:n.degree===1?5:4;x.fillStyle=selected?'#ffffff':n.degree>=3?'#f59e0b':n.degree===1?'#38bdf8':'#a78bfa';x.strokeStyle=selected?'#f59e0b':dark?'#101216':'#f4f5f7';x.lineWidth=selected?3:2;x.beginPath();x.arc(n.point.x*sx,n.point.y*sy,r,0,Math.PI*2);x.fill();x.stroke();if(selected){x.strokeStyle='#f59e0b';x.beginPath();x.arc(n.point.x*sx,n.point.y*sy,14,0,Math.PI*2);x.stroke()}})}
  p.sticks.forEach(s=>{const a=s.angle*Math.PI/180;x.strokeStyle=s.kind==='recommended'?'#36c275':s.kind==='avoid'?'#ef5350':'#e2aa2f';x.lineWidth=5;x.beginPath();x.moveTo(s.x*sx,s.y*sy);x.lineTo((s.x+Math.cos(a)*s.length/100)*sx,(s.y+Math.sin(a)*s.length/100)*sy);x.stroke()});
  if(playing&&p.lines.length){const count=Math.floor(playIndex),frac=playIndex-count;for(let i=0;i<count;i++)drawLine(p.lines[i],'#6d5dfc',Math.max(2,p.lines[i].width*2));if(count<p.lines.length){const l=p.lines[count],pts=l.points;drawLine(l,'#6d5dfc',Math.max(2,l.width*2),.25);if(pts.length>1){const segs=pts.slice(1).map((b,i)=>Math.hypot(b.x-pts[i].x,b.y-pts[i].y)),total=segs.reduce((a,b)=>a+b,0)||1;let target=total*frac,seg=0;while(seg<segs.length-1&&target>segs[seg])target-=segs[seg++];const a=pts[seg],b=pts[seg+1],u=target/(segs[seg]||1),q={x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u};x.fillStyle='#fff';x.beginPath();x.arc(q.x*sx,q.y*sy,6,0,Math.PI*2);x.fill()}}}
  x.restore();
 },[p,zoom,dark,grid,playing,playIndex,viewMode,overlayOpacity]);
 function snapshot(label:string,lines=p.lines){return{id:crypto.randomUUID(),createdAt:Date.now(),label,lines:cloneLines(lines)}}
 async function importFiles(fs:FileList|null){if(!fs)return;const files=Array.from(fs);if(!files.length)return;const processor=new BatchProcessor();setBatchOpen(true);setBatchJobs(files.map(f=>({id:crypto.randomUUID(),fileName:f.name,size:f.size,status:'queued',progress:0})));const results=await processor.runWithResults(files,p.settings.detail,j=>setBatchJobs(j));for(let i=0;i<files.length;i++){const r=results[i];if(!r)continue;const imageData=await new Promise<string>(resolve=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.readAsDataURL(files[i])});setP(q=>({...q,name:files[i].name.replace(/\.[^.]+$/,''),originalName:files[i].name,imageData,lines:cloneLines(r.lines),connections:[],history:[...q.history,snapshot('Imported '+files[i].name,q.lines)],updatedAt:Date.now()}))}processor.dispose()}
 function rebuildTopology(){setP(q=>{const graph=rebuildGraph(q.lines),connections=findConnectionCandidates(q.lines,q.settings.connectDistance),warnings=[...analyze(q.lines),...graph.filter(n=>n.degree>=3).map(n=>({id:crypto.randomUUID(),severity:'low' as const,message:'Junction node detected; review the joint before cooking.',lineIds:n.lineIds}))];return{...q,connections,warnings,sticks:recommendSticks(q.lines),updatedAt:Date.now()}})}
 function runOptimize(){const r=optimize(p.lines,p.settings);const path=minimumPenLiftPath(r.lines);const lines=path.order;const connections=findConnectionCandidates(lines,p.settings.connectDistance);const graph=rebuildGraph(lines);setP(q=>({...q,lines,connections,warnings:[...analyze(lines),...graph.filter(n=>n.degree>=3).map(n=>({id:crypto.randomUUID(),severity:'low' as const,message:'Junction node detected; review the joint before cooking.',lineIds:n.lineIds}))],sticks:recommendSticks(lines),history:[...q.history,snapshot('Sugar Artify + graph rebuild',q.lines)],updatedAt:Date.now()}))}
 function acceptConnection(id:string){setP(q=>{const connections=q.connections.map(c=>c.id===id?{...c,status:'accepted' as const}:c);return{...q,connections,updatedAt:Date.now()}})}
 function rejectConnection(id:string){setP(q=>({...q,connections:q.connections.map(c=>c.id===id?{...c,status:'rejected' as const}:c),updatedAt:Date.now()}))}
 function acceptAll(){setP(q=>({...q,connections:q.connections.map(c=>c.status==='pending'?{...c,status:'accepted' as const}:c),updatedAt:Date.now()}))}
 function applyAccepted(){setP(q=>{const before=cloneLines(q.lines),lines=applyConnections(q.lines,q.connections);const ordered=minimumPenLiftPath(lines).order,connections=findConnectionCandidates(ordered,q.settings.connectDistance).filter(c=>!q.connections.some(old=>old.a===c.a&&old.b===c.b&&old.status==='rejected'));return{...q,lines:ordered,connections,warnings:analyze(ordered),sticks:recommendSticks(ordered),history:[...q.history,snapshot('Apply accepted connections',before)],updatedAt:Date.now()}})}
 function undo(){const h=p.history.at(-1);if(!h)return;setP(q=>({...q,lines:cloneLines(h.lines),connections:findConnectionCandidates(h.lines,q.settings.connectDistance),history:q.history.slice(0,-1),updatedAt:Date.now()}))}
 function canvasPoint(e:ReactPointerEvent<HTMLCanvasElement>){const c=canvas.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left-r.width/2)/(r.width/2)/zoom,y:(e.clientY-r.top-r.height/2)/(r.height/2)/zoom}}\n function snapPoint(pt:{x:number;y:number}){if(!snap)return pt;const step=.025;let p={x:Math.round(pt.x/step)*step,y:Math.round(pt.y/step)*step};let bd=.018;for(const l of p.lines)for(const q of l.points){const d=Math.hypot(q.x-pt.x,q.y-pt.y);if(d<bd){p={...q};bd=d}}return p}
 function highlightedGraphLineIds(){if(!selectedGraphNode)return new Set<string>();const n=rebuildGraph(p.lines).find(n=>n.id===selectedGraphNode);return new Set(n?.lineIds??[])}
function graphNodeAt(pt:{x:number;y:number}){const nodes=rebuildGraph(p.lines);let best:any=null,bd=.035;for(const n of nodes){const d=Math.hypot(n.point.x-pt.x,n.point.y-pt.y);if(d<bd){bd=d;best=n}}return best}
function hitNode(pt:{x:number;y:number}){let best:{lineId:string;index:number}|null=null,bd=.028;for(const l of p.lines)for(let i=0;i<l.points.length;i++){const q=l.points[i],d=Math.hypot(q.x-pt.x,q.y-pt.y);if(d<bd){bd=d;best={lineId:l.id,index:i}}}return best}
 function hitLine(pt:{x:number;y:number}){let best:string|null=null,bd=.035;for(const l of p.lines)for(const q of l.points){const d=Math.hypot(q.x-pt.x,q.y-pt.y);if(d<bd){bd=d;best=l.id}}return best}
 function drawPoint(ev:ReactPointerEvent<HTMLCanvasElement>){const raw=canvasPoint(ev),pt=snapPoint(raw);if(graphDragging&&selectedGraphNode&&graphDragLast){
   const gn=rebuildGraph(p.lines).find(n=>n.id===selectedGraphNode);
   if(gn){
     const dx=pt.x-graphDragLast.x,dy=pt.y-graphDragLast.y;
     const ids=new Set(gn.lineIds);
     setProject(prev=>{if(!prev)return prev;const lines=prev.lines.map(l=>{if(!ids.has(l.id))return l;const points=l.points.map(q=>({...q}));if(Math.hypot(points[0].x-gn.point.x,points[0].y-gn.point.y)<=.035){points[0].x+=dx;points[0].y+=dy}const z=points.length-1;if(Math.hypot(points[z].x-gn.point.x,points[z].y-gn.point.y)<=.035){points[z].x+=dx;points[z].y+=dy}return {...l,points}});return {...prev,lines,updatedAt:Date.now()}});
     const snapRadius=.025;
     const currentGraph=rebuildGraph(lines);
     const moved=currentGraph.find(n=>n.id===selectedGraphNode);
     if(moved){
       const target=currentGraph.find(n=>n.id!==selectedGraphNode&&Math.hypot(n.point.x-moved.point.x,n.point.y-moved.point.y)<=snapRadius);
       if(target){
         const dx=target.point.x-moved.point.x,dy=target.point.y-moved.point.y;
         setProject(p=>{if(!p)return p;const merged=p.lines.map(l=>{if(!moved.lineIds.includes(l.id))return l;const points=l.points.map(q=>({...q}));if(Math.hypot(points[0].x-moved.point.x,points[0].y-moved.point.y)<=.04){points[0].x+=dx;points[0].y+=dy}const z=points.length-1;if(Math.hypot(points[z].x-moved.point.x,points[z].y-moved.point.y)<=.04){points[z].x+=dx;points[z].y+=dy}return {...l,points}});return {...p,lines:merged,connections:findConnectionCandidates(merged,p.settings.connectDistance),warnings:analyze(merged),sticks:recommendSticks(merged),updatedAt:Date.now()}});
     setGraphDragLast(pt);
     const graphNow=rebuildGraph(lines);
     const connectionsNow=findConnectionCandidates(lines,prev.settings.connectDistance);
     const warningsNow=analyze(lines);
     const sticksNow=recommendSticks(lines);
     setProject(p=>p?{...p,lines,connections:connectionsNow,warnings:warningsNow,sticks:sticksNow,updatedAt:Date.now()}:p);
   }
   return;
 }
 if(cursor==='select'){const node=hitNode(pt);if(node){setSelectedNode(node);setSelectedLine(node.lineId);setNodeDragging(true);setDragStart(pt);return}const id=hitLine(pt);setSelectedLine(id);setSelectedNode(null);if(id){setDragging(true);setDragStart(pt)}return}if(cursor==='connect'){const id=hitLine(pt);if(id){if(!connectStart)setConnectStart(id);else if(connectStart!==id){setP(q=>{const a=q.lines.find(l=>l.id===connectStart),bb=q.lines.find(l=>l.id===id);if(!a||!bb)return q;const cc=findConnectionCandidates([a,bb],q.settings.connectDistance)[0];return cc?{...q,connections:[...q.connections,cc],updatedAt:Date.now()}:q});setConnectStart(null)}}return}if(cursor==='draw'){setP(q=>({...q,lines:[...q.lines,{id:crypto.randomUUID(),points:[pt,{x:pt.x+.04,y:pt.y+.04}],width:q.settings.minWidthMm}],connections:[],history:[...q.history,snapshot('Draw',q.lines)],updatedAt:Date.now()}))}}
 function movePoint(ev:ReactPointerEvent<HTMLCanvasElement>){const raw=canvasPoint(ev),q=snapPoint(raw),dx=q.x-dragStart.x,dy=q.y-dragStart.y;if(nodeDragging&&selectedNode){setDragStart(q);setP(v=>({...v,lines:v.lines.map(l=>l.id===selectedNode.lineId?{...l,points:l.points.map((pt,i)=>i===selectedNode.index?{x:q.x,y:q.y}:pt)}:l),updatedAt:Date.now()}));return}if(!dragging||!selectedLine)return;setDragStart(q);setP(v=>({...v,lines:v.lines.map(l=>l.id===selectedLine?{...l,points:l.points.map(pt=>({x:pt.x+dx,y:pt.y+dy}))}:l),updatedAt:Date.now()}))}
 function endPoint(){setDragging(false);setNodeDragging(false);if(!snap)return;setP(q=>{const lines=q.lines.map(l=>({...l,points:l.points.map(pt=>({...pt}))}));let changed=false;for(let i=0;i<lines.length;i++)for(let j=i+1;j<lines.length;j++){for(const ai of [0,lines[i].points.length-1])for(const bj of [0,lines[j].points.length-1]){const a=lines[i].points[ai],b=lines[j].points[bj];if(Math.hypot(a.x-b.x,a.y-b.y)<.012){const m={x:(a.x+b.x)/2,y:(a.y+b.y)/2};lines[i].points[ai]=m;lines[j].points[bj]=m;changed=true}}}if(!changed)return q;const graph=rebuildGraph(lines),warnings=[...analyze(lines),...graph.filter(n=>n.degree>=3).map(n=>({id:crypto.randomUUID(),severity:'low' as const,message:'Junction node detected; review the joint before cooking.',lineIds:n.lineIds}))];return{...q,lines,connections:findConnectionCandidates(lines,q.settings.connectDistance),warnings,sticks:recommendSticks(lines),history:[...q.history,snapshot('Snap and merge endpoints',q.lines)],updatedAt:Date.now()}})}

 const pending=p.connections.filter(c=>c.status==='pending'),accepted=p.connections.filter(c=>c.status==='accepted'),rejected=p.connections.filter(c=>c.status==='rejected'),progress=p.lines.length?Math.min(100,Math.round(playIndex/p.lines.length*100)):0;
 return <div className={dark?'app dark':'app'}><header><div className="brand"><div className="logo">S</div><div><b>SugarDraw</b><small>Buildable sugar art</small></div></div><nav><button>File</button><button>Edit</button><button>View</button><button onClick={undo}><Undo2/></button><button onClick={()=>setPlayIndex(Math.max(0,playIndex-1))}><Redo2/></button><button onClick={()=>downloadSvg(p)}><Download/></button></nav><div className="topActions"><button onClick={()=>setDark(v=>!v)}>{dark?<Sun/>:<Moon/>}</button><button onClick={()=>setBatchOpen(v=>!v)}><Layers/> Batch</button><button className="primary" onClick={()=>document.getElementById('files')?.click()}><Upload/> Import</button><input id="files" hidden type="file" multiple accept=".png,.jpg,.jpeg,image/png,image/jpeg" onChange={e=>importFiles(e.target.files)}/></div></header>
 <main><aside className="toolbar"><Tool icon={<MousePointer2/>} active={cursor==='select'} on={()=>setCursor('select')} label="Select"/><Tool icon={<PenTool/>} active={cursor==='draw'} on={()=>setCursor('draw')} label="Draw"/><Tool icon={<Link2/>} active={cursor==='connect'} on={()=>setCursor('connect')} label="Connect"/><Tool icon={<Ruler/>} active={cursor==='measure'} on={()=>setCursor('measure')} label="Measure"/><Tool icon={<Move/>} active={cursor==='pan'} on={()=>setCursor('pan')} label="Pan"/><Tool icon={<ZoomIn/>} on={()=>setZoom(z=>Math.min(3,z+.2))} label="Zoom"/><Tool icon={<Grid3X3/>} active={grid} on={()=>setGrid(v=>!v)} label="Grid"/><Tool icon={<Link2/>} active={snap} on={()=>setSnap(v=>!v)} label="Snap"/><Tool icon={<Grid3X3/>} active={showNodes} on={()=>setShowNodes(v=>!v)} label="Nodes"/></aside>
 <section className="workspace"><div className="canvasWrap"><canvas ref={canvas} onPointerDown={drawPoint} onPointerMove={movePoint} onPointerUp={(e)=>{setGraphDragging(false);setGraphDragLast(null);undefined={endPoint} onPointerLeave={endPoint}/></div><div className="status"><span>Zoom {Math.round(zoom*100)}%</span><span>{grid?'Grid on':'Grid off'}</span><span>Graph: {p.lines.length} segments · {pending.length} pending</span><span>Path {totalPathLength(p.lines).toFixed(2)}u · {penLifts(p.lines)} pen lifts</span><span className="saved"><Check/> Saved locally</span></div></section>
 <aside className="panel"><div className="tabs"><b>Connections & Path</b></div><section><h3>Optimization</h3><label>Detail<select value={p.settings.detail} onChange={e=>setP(q=>({...q,settings:{...q.settings,detail:e.target.value as 'low'|'balanced'|'high'}}))}><option value="low">Simple</option><option value="balanced">Balanced</option><option value="high">Detailed</option></select></label><label>Minimum width<input type="number" step=".1" value={p.settings.minWidthMm} onChange={e=>setP(q=>({...q,settings:{...q.settings,minWidthMm:+e.target.value}}))}/> mm</label><label>Connection distance<input type="number" step=".005" value={p.settings.connectDistance} onChange={e=>setP(q=>({...q,settings:{...q.settings,connectDistance:+e.target.value}}))}/></label><button className="wide primary" onClick={runOptimize}>Rebuild Graph + Find Connections</button></section>
 <section><div className="sectionTitle"><h3>Connection Candidates</h3><span>{pending.length} pending</span></div>{pending.length>0&&<button className="wide" onClick={acceptAll}><CheckCircle2/> Accept all</button>}{pending.map((c:ConnectionCandidate,i)=><div className="connection" key={c.id}><div><b>Candidate {i+1}</b><small>{c.distance.toFixed(3)}u · {Math.round(c.angle)}° · {c.reason}</small></div><div className="row"><button onClick={()=>acceptConnection(c.id)} title="Accept"><CheckCircle2/></button><button onClick={()=>rejectConnection(c.id)} title="Reject"><XCircle/></button></div></div>)}{accepted.length>0&&<button className="wide primary" onClick={applyAccepted}><Link2/> Apply accepted ({accepted.length})</button>}{rejected.length>0&&<small>{rejected.length} rejected</small>}</section>
 <section><h3>Node Editor</h3><div className="nodeInfo">{selectedNode?'Node '+(selectedNode.index+1)+' selected':'Click a node to select it'}</div><div className="editorActions"><button disabled={!selectedNode} onClick={()=>{if(!selectedNode)return;setP(q=>({...q,lines:q.lines.map(l=>l.id===selectedNode.lineId?{...l,points:l.points.filter((_,i)=>i!==selectedNode.index)}:l).filter(l=>l.points.length>1),connections:[],history:[...q.history,snapshot('Delete node',q.lines)],updatedAt:Date.now()}));setSelectedNode(null)}}>Delete node</button><button disabled={!selectedNode} onClick={()=>{if(!selectedNode)return;setP(q=>{const l=q.lines.find(x=>x.id===selectedNode.lineId);if(!l)return q;const i=selectedNode.index,n=Math.min(i+1,l.points.length-1),a=l.points[i],bb=l.points[n],mid={x:(a.x+bb.x)/2,y:(a.y+bb.y)/2};return{...q,lines:q.lines.map(x=>x.id===l.id?{...x,points:[...x.points.slice(0,n),mid,...x.points.slice(n)]}:x),connections:[],history:[...q.history,snapshot('Add node',q.lines)],updatedAt:Date.now()}})}}>Add node</button></div></section><section><h3>Editor</h3><div className="editorActions"><button onClick={rebuildTopology}>Rebuild topology</button><button disabled={!selectedLine} onClick={()=>{if(!selectedLine)return;setP(q=>({...q,lines:q.lines.filter(l=>l.id!==selectedLine),connections:[],history:[...q.history,snapshot('Delete line',q.lines)],updatedAt:Date.now()}));setSelectedLine(null)}}>Delete</button><button disabled={!selectedLine} onClick={()=>{if(!selectedLine)return;setP(q=>({...q,lines:q.lines.map(l=>l.id===selectedLine?{...l,width:Math.max(1,l.width+.5)}:l),updatedAt:Date.now()}))}}>Thicken</button><button disabled={!selectedLine} onClick={splitSelected}>Split</button><button disabled={!selectedLine} onClick={mergeSelected}>Merge</button><button disabled={!selectedLine} onClick={measureSelected}>Measure</button></div></section><section><h3>View</h3><div className="viewModes"><button className={viewMode==='result'?'active':''} onClick={()=>setViewMode('result')}>Result</button><button className={viewMode==='original'?'active':''} onClick={()=>setViewMode('original')} disabled={!p.imageData}><ImageIcon/> Original</button><button className={viewMode==='overlay'?'active':''} onClick={()=>setViewMode('overlay')} disabled={!p.imageData}>Overlay</button></div>{viewMode==='overlay'&&<label>Overlay opacity<input type="range" min="0" max="1" step=".05" value={overlayOpacity} onChange={e=>setOverlayOpacity(+e.target.value)}/></label>}</section><section><h3>Drawing Path</h3><div className="metric"><b>{p.lines.length}</b><span>segments</span><b>{penLifts(p.lines)}</b><span>pen lifts</span></div><button className="wide" onClick={()=>{setPlayIndex(0);setPlaying(true)}} disabled={!p.lines.length}><Play/> Play simulation</button>{playing&&<button className="wide" onClick={()=>setPlaying(false)}><Pause/> Pause</button>}<button className="wide" onClick={()=>{setPlaying(false);setPlayIndex(0)}}><RefreshCw/> Reset</button></section>
 <section><h3>Structural Support Recommendation</h3>{p.warnings.length?p.warnings.slice(0,8).map(w=><div className="warning" key={w.id}><AlertTriangle/> {w.message}</div>):<div className="ok"><Check/> No detected warnings</div>}<div className="sticks">{p.sticks.map((s,i)=><div key={s.id}><b>Stick #{i+1}</b><span>{Math.round(s.angle)}° · {Math.round(s.length)} mm · {s.kind}</span></div>)}</div></section>
 <section><h3>Project</h3><input value={p.name} onChange={e=>setP(q=>({...q,name:e.target.value}))}/><div className="row"><input value={p.widthMm} type="number" onChange={e=>setP(q=>({...q,widthMm:+e.target.value}))}/><span>×</span><input value={p.heightMm} type="number" onChange={e=>setP(q=>({...q,heightMm:+e.target.value}))}/><span>mm</span></div><button className="wide" onClick={()=>planPdf(p)}>Production Plan PDF</button><button className="wide" onClick={()=>zipProjects([p])}>Export ZIP</button></section>
 <section><h3>Saved Projects</h3>{projects.slice(0,5).map(x=><button className="project" key={x.id} onClick={()=>setP(normalize(x))}><FolderOpen/> {x.name}</button>)}</section></aside></main>
 {batchOpen&&<div className="batchPanel"><div className="batchHead"><b>Batch Processing</b><button onClick={()=>setBatchOpen(false)}>×</button></div>{batchJobs.length===0?<p>Import multiple PNG/JPEG files to start a local worker queue.</p>:batchJobs.map(j=><div className="job" key={j.id}><div><b>{j.fileName}</b><small>{Math.round(j.size/1024)} KB · {j.status}</small></div><div className="bar"><i style={{width:j.progress+'%'}}/></div>{j.status==='done'?<Check/>:j.status==='error'?<AlertTriangle/>:null}</div>)}</div>}
 {playing&&<div className="player"><Play/> Drawing simulation · {progress}%</div>}<footer><button onClick={()=>{setPlayIndex(0);setPlaying(true)}}><Play/> Play Drawing Simulation</button><span>Local processing · Graph/path reconstruction is geometric; structural analysis is heuristic, not material simulation.</span></footer></div>
}
function Tool({icon,label,on,active}:{icon:ReactNode;label:string;on:()=>void;active?:boolean}){return <button className={active?'tool active':'tool'} onClick={on}>{icon}<small>{label}</small></button>}
